baseURL = 'https://sinsiway-official.github.io'


defaultContentLanguage = "ko"
# enableMissingTranslationPlaceholders = true
# enableRobotsTXT = true
# enableGitInfo = true


[languages]
  [languages.en]
    title = "Sinsiway Docs"
    description = "Sinsiway API Guide Document"
    weight = 1
    contentDir = "content/en"
    languageCode = 'en-us'
    languageName ="English"
    time_format_default = "02.01.2006"
    time_format_blog = "02.01.2006"
  [languages.ko]
    title = "Petra Cipher Docs"
    description = "신시웨이 Petra Cipher 라이브러리 문서"
    weight = 2
    contentDir = "content/ko"
    languageCode = "ko-KR"
    languageName ="한국어"
    time_format_default = "2006.01.02"
    time_format_blog = "2006.01.02"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"



# [languages]
# [languages.en]

# description = "Sinsiway API Guide Document"
# languageName ="English"
# # Weight used for sorting.
# weight = 1


# [languages.ko]


# languageName ="한국어"
# # Weight used for sorting.
# weight = 2


[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "dracula"



[params]
copyright = "Inc Sinsiway."
favicon = "favicon.ico"
# favicon_ico_sizes = "16x16 32x32"
# privacy_policy = "https://policies.google.com/privacy"
# github_repo = "https://github.com/sinsiway-official/sinsiway-official.github.io"

[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to disable the About link in the site footer
footer_about_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false


[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "dummy"

[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = '소중한 의견 감사합니다. <a href="https://github.com/sinsiway-official/sinsiway-official.github.io/issues/new">귀하의 소중한 의견 부탁드립니다.</a>.'
no = '피드백을 주시면 더 나은 서비스를 제공할 수 있도록 노력하겠습니다. <a href="https://github.com/sinsiway-official/sinsiway-official.github.io/issues/new">귀하의 소중한 의견 부탁드립니다.</a>.'

[module]
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"


